# Generated by Django 3.2.7 on 2021-10-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JigyasaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
