# Generated by Django 3.2.7 on 2021-11-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JigyasaApp', '0006_schedulemeeting_studentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemeeting',
            name='meeting_password',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='schedulemeeting',
            name='meeting_url',
            field=models.CharField(default='', max_length=600),
        ),
    ]
