# Generated by Django 3.2.7 on 2021-11-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JigyasaApp', '0008_alter_schedulemeeting_meeting_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulemeeting',
            name='meeting_url',
        ),
        migrations.AddField(
            model_name='schedulemeeting',
            name='join_url',
            field=models.CharField(default='', max_length=6000),
        ),
        migrations.AddField(
            model_name='schedulemeeting',
            name='start_url',
            field=models.CharField(default='', max_length=6000),
        ),
    ]
