# Generated by Django 3.2.7 on 2021-11-07 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JigyasaApp', '0009_auto_20211106_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareNotes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(default='', max_length=255)),
                ('notes', models.FileField(upload_to='media/Notes')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JigyasaApp.staffs')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JigyasaApp.subjects')),
            ],
        ),
    ]
